
require('pluggins')
require('settings')
require('keymappings')
require('colorscheme')

require('pluggin-config.nvimtree')
require('pluggin-config.telescope')
require('pluggin-config.treesitter')
require('pluggin-config.toggleterm')
require('pluggin-config.lualine')
require('pluggin-config.bufferline')
require('pluggin-config.lsp')
require('pluggin-config.cmp')
require('pluggin-config.gitsigns')
require('pluggin-config.autopairs')
require('pluggin-config.whichkey')
require('pluggin-config.indent')
require('pluggin-config.noice')
require('pluggin-config.animate')
require('pluggin-config.colorizer')
